# DATATYPES IN NUMPY

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object 

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5],dtype ="S")
print(type(a))

<class 'numpy.ndarray'>


In [6]:
# 4 bytes dtype
a=np.array([1,2,3,4,5],dtype="i4")
a.dtype

dtype('int32')

In [8]:
a=np.array([1.1,1.2,1.3,1.4])
new_a=a.astype("i")# converts float into integer
print(new_a)
new_a.dtype


[1 1 1 1]


dtype('int32')

In [14]:
a=np.array([1,0,3,1])
new_a=a.astype(bool)
print(a)
print(new_a)
new_a.dtype

[1 0 3 1]
[ True False  True  True]


dtype('bool')

### NumPy Array Copy vs View

In [15]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.copy()
print(a[1])
print(b)

2
[1 2 3 4 5 6 7 8 9]


In [17]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
b=a.copy()
a[0]="89"
print(a)
print(b)

[89  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]


In [18]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.view()
print(a[1])
print(b)

2
[1 2 3 4 5 6 7 8 9]


In [19]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.view()
a[0]=78
print(a)
print(b)

[78  2  3  4  5  6  7  8  9]
[78  2  3  4  5  6  7  8  9]


In [20]:
a=np.array([1,2,3,4,5,6,7,8,9])

c=a.copy()
v=a.view()

print(a.base)
print(b.base)

None
[78  2  3  4  5  6  7  8  9]


### NumPy Array Shape

#### Shape of an Array
The shape of an array is the number of elements in each dimension.

Get the Shape of an Array :

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [22]:
a=np.array([1,2,3,4,5,6,7,8,9,0])
b=np.array([[1,2,3,4,5],[6,7,8,9,0]])
c=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

In [27]:
print(a.shape)
print(a.ndim)

(10,)
1


In [28]:
print(b.shape)
print(b.ndim)

(2, 5)
2


In [29]:
print(c.shape)
print(c.ndim)

(2, 2, 5)
3


### NumPy Array Reshaping

Reshaping arrays:

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [33]:
a=np.array([0,1,2,3,4,5,6,7,8,9,10,11])
new_a=a.reshape(4,3)
print(new_a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [37]:
b=np.array([1,2,3,4,5,6,7,8,9])
new_b=b.reshape(3,3)
print("ORIGINAL ARRAY",b)
print("RESHAPED ARRAY:",new_b)

ORIGINAL ARRAY [1 2 3 4 5 6 7 8 9]
RESHAPED ARRAY: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_a=a.reshape(2,3,2)
print(a)
print(new_a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [40]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_a=a.reshape(2,6).base
print(new_a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### The example above returns the original array, so it is a view.

In [41]:
a=np.array([[1,2,3,4,5],[6,7,8,9,0]])
new_a=a.reshape(-1)
print(a)
print(new_a)

[[1 2 3 4 5]
 [6 7 8 9 0]]
[1 2 3 4 5 6 7 8 9 0]


In [42]:
c

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [43]:
new_c=c.reshape(-1)
print(new_c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### NumPy Array Iterating

Iterating Arrays:
    
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [46]:
a=np.array([1,2,3,4,5,6,7,8])

for i in a:
    print(i)

1
2
3
4
5
6
7
8


In [50]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])

for i in b :
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [51]:
c=np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])

for i in c:
    print(i)

[[1 2 3]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


### Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. 

It solves some basic issues which we face in iteration, lets go through it with examples.

### Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [53]:
a=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
print(a)
for i in np.nditer(a):
    print(i)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]
1
2
3
4
5
6
6
7


In [56]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
for i in np.nditer(a[:,::2]):
    print(i)

[[1 2 3 4]
 [5 6 7 8]]
1
3
5
7


### Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [57]:
a=np.array([[1,2,3,4],[5,6,7,8]])

for i,j in np.ndenumerate(a):
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [58]:
a=np.array([1,2,3])
b=np.array([4,5,6])

ab=np.concatenate((a,b))
print(ab)

[1 2 3 4 5 6]


In [63]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6], [7, 8]])


ab=np.concatenate((a,b),axis=1)
print(ab)

[[1 2 5 6]
 [3 4 7 8]]


In [66]:
a=np.array([1,2,3])
b=np.array([4,5,6])

ab=np.stack((a,b),axis=1)
print(ab)

[[1 4]
 [2 5]
 [3 6]]


In [68]:
a=np.array([1,2,3])
b=np.array([4,5,6])

ab=np.hstack((a,b))
print(ab)

[1 2 3 4 5 6]


In [69]:
a=np.array([1,2,3])
b=np.array([4,5,6])

ab=np.vstack((a,b))
print(ab)

[[1 2 3]
 [4 5 6]]


In [70]:
a=np.array([1,2,3])
b=np.array([4,5,6])

ab=np.dstack((a,b))
print(ab)

[[[1 4]
  [2 5]
  [3 6]]]


### NumPy Splitting Array:

# Splitting NumPy Arrays:
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [71]:
a=np.array([1,2,3,4,5,6,7,8,9])

new_a=np.array_split(a,3)

print(new_a)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [72]:
b=np.array([1, 2, 3, 4, 5, 6])

new_b=np.array_split(b,4)

print(new_b)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### NumPy Searching Arrays:

### Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [73]:
a=np.array([1, 2, 3, 4, 5, 6])

e=np.where(a == 3)

print(e)

(array([2], dtype=int64),)


In [74]:
a=np.array([1, 2, 3, 4, 5, 6,3,4,1,3,5,3])

x=np.where(a == 3)

print(x)

(array([ 2,  6,  9, 11], dtype=int64),)


In [78]:
a=np.array([1, 2, 3, 4, 5, 6,7,8])

x=np.where(a%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [77]:
b=np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(b%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [79]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [80]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, [7,8])

print(x)

[1 2]


### NumPy Sorting Arrays

# Sorting Arrays
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [81]:
a=np.array([1,3,4,5,8,9,0,2])
print(np.sort(a))

[0 1 2 3 4 5 8 9]


In [82]:
a=np.array(["Omkar","Yash","Anushree","Prathamesh","omkar","yashshree"])
print(np.sort(a))

['Anushree' 'Omkar' 'Prathamesh' 'Yash' 'omkar' 'yashshree']


In [85]:
a=np.array([[7,5,1],[61,21,3]])
print(np.sort(a))

[[ 1  5  7]
 [ 3 21 61]]


### NumPy Filter Array

### Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

In [88]:
a=np.array([1,2,4,5])
b=np.array([True,False,False,True])

c=a[b]
print(c)

[1 5]


In [90]:
a=np.array([0,1,2,3,4,5,6,7,8,9])

fil_a=[]

for i in a:
    if i % 2==0:
        fil_a.append(True)
    else:
        fil_a.append(False)

c=a[fil_a]

print(a)
print(c)
print(fil_a)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[True, False, True, False, True, False, True, False, True, False]


In [92]:
a=np.array([0,1,2,3,4,5,6,7,8,9])

fil_a=a>3

c=a[fil_a]

print(a)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]


In [97]:
a=np.array([0,1,2,3,4,5,6,7,8,9])

fil_a=a%3==0

c=a[fil_a]

print(a)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[0 3 6 9]
