# Numpy

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

### What is NumPy?
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [1]:
import numpy as np
import pandas as pd

In [3]:
a=np.array([1,2,3,4,5,6,7,8,9,0])
print(a)

[1 2 3 4 5 6 7 8 9 0]


In [5]:
print(np.__version__)

1.24.3


In [6]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(type(a))

<class 'numpy.ndarray'>


In [7]:
b=np.array((1,2,3,4,5))
print(b)

[1 2 3 4 5]


In [8]:
a=np.array(42)
print(a)

42


### One Dimension Array :

In [9]:
a=np.array([1,2,3,4,5,6])#1D Array
print(a)

[1 2 3 4 5 6]


### Two Dimensional Array :

In [11]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [12]:
a=np.array([[0,2,4,6,8],[1,3,5,7,9]])
print(a)

[[0 2 4 6 8]
 [1 3 5 7 9]]


In [13]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
b=np.array([[[1,4,9],[16,25,36]],[[49,64,81],[100,121,144]]])
print(b)

[[[  1   4   9]
  [ 16  25  36]]

 [[ 49  64  81]
  [100 121 144]]]


In [16]:
c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [50]:
a=np.array([1,2,3,4,5])
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [23]:
d=np.array([1,2,3,4,5],ndmin=5)

print(d)

[[[[[1 2 3 4 5]]]]]


In [25]:
print(a[0])
print(a[1])
print(a[2])

1
2
3


In [29]:
print(b[1])
print(b[0])

[4 5 6]
[1 2 3]


In [34]:
print(c[0])

print(c[1])


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [35]:
print(a[1]+a[2])

5


In [36]:
print(b[0]+b[1])

[5 7 9]


In [42]:
print(b)
print(b[0,1])
print(b[1,0])
print(b[1,1])

[[1 2 3]
 [4 5 6]]
2
4
5


In [54]:
print(c)
print(c[0,0,1])
print(c[0,1,0])
print(c[1,1,0])
print(c[1,0,0])
print(c[1,0,2])
print(c[1,1,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
2
4
10
7
9
11


In [74]:
print(b)
print(b[1,0])
print(b[0,-1])
print(b[0,-2])

[[1 2 3]
 [4 5 6]]
4
3
2


### NumPy Array Slicing

Slicing arrays :
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [75]:
print(a)

[1 2 3 4 5]


In [79]:
print(a[0:3])

[1 2 3]


In [80]:
print(a[2:])

[3 4 5]


In [81]:
print(a[:4])

[1 2 3 4]


In [91]:
print(a)
print(a[-4:-1])

[1 2 3 4 5]
[2 3 4]


# Steps

In [92]:
print(a)

[1 2 3 4 5]


In [94]:
print(a[0:5:2])

[1 3 5]


In [97]:
print(a[::2])

[1 3 5]


In [98]:
print(a[1::])

[2 3 4 5]


In [100]:
print(a[1::])

[2 3 4 5]


### Sliciing (2D Array)

In [103]:
print(b)
print(b[0,0:2])

[[1 2 3]
 [4 5 6]]
[1 2]


In [106]:
b=np.array([[0,1,2,3,4,5,6,7],[8,9,10,11,12,13,14,15,]])
print(b)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [110]:
print(b[0,0:6])
print(b[0,0:7:2])
print(b[1,0:5])


[0 1 2 3 4 5]
[0 2 4 6]
[ 8  9 10 11 12]


In [112]:
print(b[0:2,2])

[ 2 10]


In [116]:
print(b[0:2,3])

[ 3 11]


In [117]:
print(b[0:2,2:4])

[[ 2  3]
 [10 11]]


In [119]:
print(b.dtype)

int32


In [120]:
a=np.array(["Omakr","Yash","Aishwariya","Anushree"])
print(a.dtype)

<U10


In [121]:
a=np.array([1,2,3,4,5],dtype="S")

print(a)

[b'1' b'2' b'3' b'4' b'5']
